[logging]
history-size = 20

[arbitrer]
retry-delay = 60    # [minutes]
bet-size = 5.00     # [$]
history-size = 48   # [hours]

lower-profit-threshold = 0.01
upper-profit-threshold = 0.05

[server]
port = 3000

[[bookies]]
host = "egamingbets.com"
username = "shmaladdin"
password = "aladdin"

[[bookies]]
host = "vitalbet.com"
username = "Алладин"
password = "aladdin"

[[bookies]]
host = "1xsporta.space"
username = "shmaladdin.rs@gmail.com"
password = "aladdin.rs"

[[bookies]]
host = "cybbet.com"
username = "aladdin"
password = "Shmaladdin42"
