#!/bin/sh

set -e

TARGET=x86_64-unknown-linux-gnu
FLAGS=--features="place-bets"
MODE=debug
USER=aladdin
HOST=46.101.244.208
DIR=\~
MAIN=aladdin
LOG=aladdin.log
ENV="RUST_LOG=${RUST_LOG:=aladdin=info} TZ='Europe/Moscow'"

if [ $MODE == release ]; then
    FLAGS="--release $FLAGS"
fi

function remote {
    ssh -t "$USER@$HOST" "$1"
}

STATUS_CMD="start-stop-daemon --status --chdir $DIR --exec $MAIN"
START_CMD="$ENV start-stop-daemon --start --oknodo --no-close --background --chdir $DIR --exec $MAIN > $LOG 2>&1"
STOP_CMD="start-stop-daemon --stop --oknodo --retry 10 --chdir $DIR --exec $MAIN"
LOG_CMD="less -R +F $LOG"

case "$1" in
    deploy)
        cargo build --target=$TARGET $FLAGS
        scp "target/$TARGET/$MODE/aladdin" "$USER@$HOST":~
        ;;

    status)
        set +e
        remote "$STATUS_CMD"
        case "$?" in
            0) echo 'Aladdin is running' ;;
            1|3) echo 'Aladdin is not running' ;;
            4) echo 'Unable to determine status' ;;
        esac
        ;;

    log) remote "$LOG_CMD" ;;
    start) remote "$START_CMD" ;;
    stop) remote "$STOP_CMD" ;;
    restart) remote "$STOP_CMD && $START_CMD" ;;

    *)
        echo "Usage: "$1" {deploy|log|status|start|stop|restart}"
        exit 1
esac
